### ISSUE TITLE
Save active configuration and platform

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#96] opened 2020-03-26 08:52 UTC
When reopening projects it always defaults to Win64 / Debug, which means i'm constantly changing it to Win32 :/

**Comment by bfiete** [comment] 2020-03-26 13:21
Hm. I'm having trouble reproducing this issue... 
In your BeefSpace_User.toml file, do you see `LastPlatform = "Win32"`?
Do you open the workspace by selecting 'File / Open Recent / Open Recent Workspace' or some other way?

**Comment by bfiete** [comment] 2020-03-26 13:22
Oh actually, I do see exactly what the issue is now, looking at the code.

**Comment by bfiete** [comment] 2020-03-26 14:04
Should be fixed here https://github.com/beefytech/Beef/commit/24dd60933bd37c0593987f08c883a8976613226e

**Comment by damianday** [comment] 2020-03-26 15:56
> Hm. I'm having trouble reproducing this issue...
> In your BeefSpace_User.toml file, do you see `LastPlatform = "Win32"`?
> Do you open the workspace by selecting 'File / Open Recent / Open Recent Workspace' or some other way?

Yeah most of the time

**Closed** 2020-03-26 18:08 UTC
