### ISSUE TITLE
BFGC crash on my c htread

### ISSUE THREAD

**Issue by kochol** [beefytech/Beef#252] opened 2020-05-13 07:10 UTC
Hi

I have two threads in my c++ DLL and when gc.cpp line 1450 wants to calculate the length, stackPtr is bigger than thread->mStackStart so the length became negative or even overflow then it will crash on gc.cpp line 789 because the value is null.

https://github.com/beefytech/Beef/blob/5e5084886c4eed6ca12199d23cb4f3613ec3792b/BeefRT/dbg/gc.cpp#L1450

https://github.com/beefytech/Beef/blob/5e5084886c4eed6ca12199d23cb4f3613ec3792b/BeefRT/dbg/gc.cpp#L789

For now, I added this code for myself to ignore the crash until a fix comes for this.
```
		if (stackPtr > thread->mStackStart)
			continue;
```

**Comment by bfiete** [comment] 2020-05-13 14:50
I haven't ever seen this happen, this shouldn't be possible. Is there anything unusual about your threads? This is reproducible for you?

**Comment by bfiete** [comment] 2020-05-13 15:23
When this occurs- you should be able to switch into that thread and inspect the RSP register at the top and bottom of its callstack to get an estimate of the stack range. Either "stackPtr' or "thread->mStackStart" are wrong - which one? And is it VERY wrong or slightly wrong?

**Comment by kochol** [comment] 2020-05-13 18:49
It is very wrong that makes length overflow. usually, stackPtr is a very big number.

**Comment by bfiete** [comment] 2020-05-13 19:14
So the "thread->mStackStart" does approximately match the RSP at the bottom of the callstack?

**Comment by kochol** [comment] 2020-05-14 03:12
Let me investigate more maybe I'll find the bug.

**Comment by kochol** [comment] 2020-05-14 04:48
> 
> 
> So the "thread->mStackStart" does approximately match the RSP at the bottom of the callstack?

yes

**Comment by kochol** [comment] 2020-05-14 04:49
I use this library for creating fibers
and it makes stack on virtual memory

https://github.com/septag/sx/blob/2936084449546788ba59bad44a47f036220c9e40/src/fiber.c#L41-L47

**Comment by kochol** [comment] 2020-05-14 06:36
I think in this thread it changes stack pointer for each fiber.

**Comment by kochol** [comment] 2020-05-15 03:01
Your code gets RSP register correctly, the fibers also work good but they change the RSP register so it makes Beef GC crash but this is not the only problem the GC will report memory leak for every single object that I have in my beef program.

I tested a lot but when I disable fibers in my code the codes run fine and there is no more memory leak error in my project.

Is there any option to disable GC at least in release builds?

**Comment by bfiete** [comment] 2020-05-15 12:22
You can disable it in the Workspace/Beef properties under "Realtime Leak Check". I'll work on a fix, it may just be a case of caching the stack base where we should be retrieving it every GC cycle.

**Comment by bfiete** [comment] 2020-05-16 19:28
Potential fix at https://github.com/beefytech/Beef/commit/4472449cc40fa3cd27bdf1844878c63e58744378, will be in 0.42.4.

**Comment by kochol** [comment] 2020-05-17 16:04
Yes, I can confirm its fixed.

But the problem with wrong leaked objects is remain. Do I need to open a new issue for that?

**Comment by bfiete** [comment] 2020-05-17 16:21
Mm, that's not good. It's also a bit strange - presumably no Beef code is actually running on these threads that are being used for fibers, right? Or are they? Actually that could be real issue - the GC would have no way to scan the stacks of non-active fibers.

**Comment by kochol** [comment] 2020-05-17 17:49
Yes, you're right there is no beef code on these fibers threads. I don't know the logic behind the leak detector, why the other threads make bug for it.

If you want I can send the code for testing.

**Comment by bfiete** [comment] 2020-05-17 18:06
Oh, yes, it would be quite useful for me to be able to reproduce it on my side. If you don't want to post the code here you can email it to beef@beefytech.com.

**Comment by kochol** [comment] 2020-05-18 02:24
My project is open source actually. https://github.com/kochol/ariyana.git you can read how to build section in the readme. I provide the needed commands to compile below.

please make a new directory for my project, for example, fips_workspace and clone it there.

You need 
- git 
- python 2 or 3
- cmake

```
mkdir fips-workspace
cd fips-workspace
git clone https://github.com/kochol/ariyana.git
cd ariyana
fips gen
fips make cari
cd ..
git clone https://github.com/kochol/Ariyana_beef.git
cd Ariyana_beef\dist
copy_dll.bat
```
After that, you can open the Ariyan_beef project in beef ide and test it with t02Network test project.

You can disable or enable fibers by uncommenting or commenting the line 13 in ariyana\src\c99\en.cpp file and build again with

```
cd ariyana
fips make cari
..\Ariyana_beef\dist\copy_dll.bat
```

By default, I **disabled** the fibers for Beef bindings.

**Comment by bfiete** [comment] 2020-05-18 17:52
This fiber library will also schedule fibers on the main thread - I have caught it inside `fiber_fn` on the main thread with a new stack set up... and then the leak immediately after that, of course.

Theoretically this can be resolved- if the fiber library were to expose the saved stack information from the threads currently running fibers, you can use `GC.AddRootCallback`, and then perform a `GC.Mark(void* ptr, int size)` on those ranges. All non-executing fiber stacks ranges were exposed then you could theoretically even run Beef code in fibers.

There are some constraints with the marking system - most notably that the world is stopped when they run, so it is easy to deadlock by calling anything at all that locks. Custom marking routines should follow lock-free patterns with volatile writes and memory barriers and such, and the data must be designed so it is valid at any frozen state (because, again, you cannot lock).

**Comment by bfiete** [comment] 2020-05-22 13:32
Closing since this isn't actually a bug on our end. I would be interested in having the above attempted to "prove" that the Beef GC can work with fibers, however!

**Closed by bfiete** 2020-05-22 13:32 UTC
Labels: bug, fixed
