### ISSUE TITLE
Strange IDE Crash (0.42.4)

### ISSUE THREAD

**Issue by MattThorson** [beefytech/Beef#290] opened 2020-05-23 04:57 UTC
This report may not be useful because of the nature of the bug, but it's consistent so it seemed worth posting. Hopefully the crash dump is helpful [(here)](https://github.com/beefytech/Beef/files/4671147/crashDump.zip)

I have a workspace on my machine that I can consistently crash with the following steps:
1- Open workspace
2- Run once with F5
3- Change anything in a bf file and save (just adding white space works)
4- Run again with F5, IDE crashes

I tried Clean, and Clean Beef, but they didn't help.

The strange part is, I copied the workspace out to a fresh folder to try and isolate the bug, but the copied workspace, identical in every way except location, doesn't crash the IDE at all. It's nice that I can work on my project in that copied directory fine going forward, but it also makes it hard to give you a repro case.

**Comment by bfiete** [comment] 2020-05-24 13:24
Is the crashy folder something you can zip up and send? The crash dump is useful and I'm confident I can fix the crash on that alone, but a reproducible case would be helpful to ensure I completely understood and addressed the root cause.

**Comment by MattThorson** [comment] 2020-05-24 21:17
I emailed you with the project folder and latest crash dump, thanks

**Comment by bfiete** [comment] 2020-05-25 14:29
This was an interaction with `[Reflection]` and `[Inline]` on `Actor`. Fixed in https://github.com/beefytech/Beef/commit/92ccadce1e3af2fc4df3a74d4716629365788c88.

Also- I have set up a nightly build system (link on README.md and on beeflang.org). The current build has this fix applied.

**Closed by bfiete** 2020-05-25 14:29 UTC
Labels: bug

**Comment by MattThorson** [comment] 2020-05-25 17:37
Awesome! I'll get on the nightly builds.
