### ISSUE TITLE
Wrong constructor called during Test

### ISSUE THREAD

**Issue by damianday** [beefytech/Beef#36] opened 2020-01-25 13:11 UTC
```
using System;
using System.Diagnostics;

namespace Buffer
{
	class CircularBuffer
	{
		private const int DefaultSize = (1024 * 2);

		public uint8[] _data;

		public this(int size = DefaultSize)
			: base ()
		{
			Debug.Assert(size > 0);
			_data = new uint8[size];
		}
	
		[Test]
		public static void TestBuffer()
		{
			var buffer = new CircularBuffer();
			Debug.Assert(buffer._data.Count == CircularBuffer.DefaultSize);
		}
	}
}
```

Running the above test in debug mode seg faults _data is not allocated, only seems to happen during testing.

**Comment by bfiete** [comment] 2020-01-26 14:50
Fixed - will be in 0.42.2. The problem is that the compiler always creates a parameterless constructor even if you don't define one yourself, but it set the visibility to 'private' if you explicitly define other constructors. But that private parameterless constructor still was visible within methods of that class, which was wrong. 

The visibility is now 'hidden' which properly disallows user code from calling it directly, but still allows it to be called indirectly (at runtime with reflection, for example).

**Closed** 2020-02-22 12:17 UTC
