### ISSUE TITLE
Project name and logo can hurt people's sensibilities

### ISSUE THREAD

**Issue by hamoid** [beefytech/Beef#14] opened 2020-01-10 11:09 UTC
Hi! Thank you for releasing this project. I'm often looking for a language that is powerful and fast to compile that helps with experimentation :)

This issue may sound like a joke but it's not. I find it uncomfortable to look at a logo representing a sliced dead animal. Growing large animals for human consumption is also a contributor to the climate problem. I guess so far I'm part of a small but growing minority, but I thought I should still raise awareness to this. I know changing a name is a hard issue to fix. 

Maybe Beef could be an acronym of something less bloody and the logo match that acronym?

Or if the authors are strong believers in raising animals for human consumption an option would be to fork the project and replace every mention of Beef with another word to appeal to a wider audience? Leaf sounds similar and has the same number of characters, but leaf-lang exists already.

In any case thank you for considering this.

**Comment by LucaSoato** [comment] 2020-01-10 12:54
Beef is such a common word that finding resources or documentation for the project is going to be very hard in the future, but BF is also the author's name initials 😕

**Comment by bfiete** [comment] 2020-01-10 13:08
I'd say a the logo already must change for this reason: it's not _uniquely_ representative of the programming language itself. If you were to see the logo in isolation, you would not think "hey, that's BeefLang!" the same way you would for the Rust, Swift, or Python logos.

Honestly it was just chosen because I need some sort of icon and that was the laziest choice. If someone were to submit something even slightly better then that would be the new logo -- until someone thinks of something even better than that!

**Comment by rafaelvasco** [comment] 2020-01-10 16:55
Something old school demo scene style logo would be great :)

**Comment by Coalpha** [comment] 2020-01-11 06:18
First of all, I think this is a great project. Thanks for sharing it!
I agree with the change in logo but for another reason. I recognized it from Restaurant City, a game that's owned by Playfish. It's actually supposed to be [lamb](https://restaurantcity.fandom.com/wiki/Lamb). I don't know if they own the rights to that artwork but better to be safe, right?

**Comment by tjpalmer** [comment] 2020-02-06 12:33
There's also the entire Hindu population of the planet that might be turned off. I'm not Hindu myself, so maybe I'm wrong. But that's what came to mind immediately to me.

**Comment by stefanos82** [comment] 2020-03-03 01:52
I guess calling it **BriFi** that rhymes with "Beefy" would be a lot better on so many levels.

**Comment by sukhchainn** [comment] 2020-04-02 15:37
<img src="https://github.com/sukhchainn/img/blob/master/Project_-_Drawing_11151544218665422638%5B1%5D.png?raw=true" width="200px" height="200px">

I made this. 
It's not much, but it's an honest work.

**Comment by dmatking** [comment] 2020-04-02 16:40
It's nice. Is there a meaning behind your design and color selections?

**Comment by sukhchainn** [comment] 2020-04-03 09:31
@hamoid mentioned Leaf so I thought this would go well with the name, but to be honest I thought that logo should be simple and easy to remember.

**Comment by sacredbirdman** [comment] 2020-04-11 21:02
![beef_logo](https://user-images.githubusercontent.com/43012733/79054812-be4a7500-7c50-11ea-9228-d0bff23b39f3.png)
Here's a simple idea based on the current name.

**Comment by Phischermen** [comment] 2020-04-24 17:49
Since the language's main goal is to be more performant than C#, maybe you could do a logo with a flexing bicep? So rather than beef as in meat, its beef as in muscle.

**Comment by Phischermen** [comment] 2020-04-24 17:57
> 
> 
> Beef is such a common word that finding resources or documentation for the project is going to be very hard in the future

I agree with this. What if the name was changed to "Beef#"? I'm sure that will make it easier to find resources for online.

**Comment by sukhchainn** [comment] 2020-04-24 19:12
> 
> 
> > Beef is such a common word that finding resources or documentation for the project is going to be very hard in the future
> 
> I agree with this. What if the name was changed to "Beef#"? I'm sure that will make it easier to find resources for online.

Or maybe #Beef ? It would make finding tutorials easier online for noobs.

**Comment by awulkan** [comment] 2020-04-24 19:58
I don't personally have a beef with the name. However it did make me think that this project was just a joke. It's not the kind of name I'd give a project that I wanted to succeed, if you get what I'm saying. I can't imagine me saying "We should try doing this project in beef" at a meeting. Maybe it's just me though.

Also, in terms of SEO it would be impossible to rank high in search engines, unless you're fine with people having to search for things like "beef lang".

Anyway, good luck with the language, it looks interesting. :)

**Comment by xinaesthete** [comment] 2020-04-26 09:08
> ![beef_logo](https://user-images.githubusercontent.com/43012733/79054812-be4a7500-7c50-11ea-9228-d0bff23b39f3.png)
> Here's a simple idea based on the current name.

Looks pretty good but why not further simplify by removing the orange drag-handle type things or whatever they are?

**Comment by Grinshpon** [comment] 2020-04-26 21:31
Why is this issue still open? A game-centered programming language is not the place for vegan protests

**Comment by sukhchain99** [comment] 2020-04-27 00:39
> Why is this issue still open? A game-centered programming language is not the place for vegan protests

Every life matters and every vote counts. I don't think offending vegan programmers will get this project far and negative publicity doesn't work well for Programming projects. 

Proof: Corona SDK.

**Comment by Grinshpon** [comment] 2020-04-27 00:45
Is there really a community of vegan programmers that get offended by the mention or sight of meat?

**Comment by ReeceSX** [comment] 2020-04-27 02:37
> Is there really a community of vegan programmers that get offended by the mention or sight of meat?

Is there really a community of vegan programmers that get offended by the sight of meat? I'm not sure. Is there a community of rampant elitists that go out of their way to shun replies with reactions to create the illusion of support behind an exclusive idea. Hacking has historically been an inclusive community to such an extent the only requirements were a shitty modem and a computer; the most divisive thing to exist was the GIMP abbreviation. Slapping a rendition of meat, a produce 8% of the worlds population has deemed immoral, is the last thing any sane project manager should consider. Why yes we should turn away 15%⋂8%  of potential gamedevs, langdevs, and related

**Comment by Bigalan09** [comment] 2020-04-27 14:30
It a difficult one.  For me, I really like the idea of this project and I would hate to see it fail because of a name and icon. 
Imagine A few years down the line and colleges are teaching "beef"? it doesn't sound appealing.

**Comment by sukhchain99** [comment] 2020-04-27 14:33
At least change the logo. The worst thing possible for this Project can be, either it gets abandoned or a copyright claim. The name beef doesn't affect the market image as the logo does. It's a really cartoonish logo which misrepresents the language's capabilities, if I hadn't watched the video by GameFromScratch then I wouldn't have considered learning it. I think the logo should be changed at least for now.

**Comment by animehunter** [comment] 2020-04-28 04:07
I strongly agree that this project needs a name/logo change. It would be a huge shame to it get abandoned since it has so much potential to become the next big programming language for game devs, system devs, backend devs, etc. 

It's not too late to change it now especially since the party is only getting started.

**Comment by GH-TheRaven-06835** [comment] 2020-04-28 04:12
I'm voting for Cheese Burger

**Comment by EnokViking** [comment] 2020-04-28 08:19
I partly agree, the language sort of comes off as your typical troll language, e.g. "lolcode" and doesn't properly convey that it is in fact a serious thing, but changing the name just because "it might offend someone" is just all wrong and frankly, straight out regressive.  That said, something that conveys it as a C-family language is probably more beneficial in the long run.

**Comment by raizam** [comment] 2020-04-28 21:54
I vote for Bean, it's a good alternative to Beef as it has as much protein

**Comment by MissKraya** [comment] 2020-04-30 13:27
Just throwing my 2c in here but the name Beef is just dumb imo... I found this while scouting for a more performant language than C# but more modern than C++ for my side-project.

My project is going to be a huge undertaking and I dont really want one of my crowning achievements to be "wrote a game engine in Beef". Getting any studio to take it seriously will be a difficult job too, "check out this new game oriented language called Beef"... management isn't gonna see past that without some serious arguing. 

@EnokViking is 100% right... this isnt about offending people, it's about actually being taken seriously as a C# competitor and not just a group of bros who are looking for laughs.

**Comment by awulkan** [comment] 2020-04-30 16:42
@bfiete In that case I guess you can close this issue. It's in your full right to name it whatever you want of course. We're all just a bunch of random people with opinions. If the language name is already set in stone we're all just wasting time here discussing it.

Maybe it's better to open another issue just for the logo change, since you brought up that you wanted to change it?

I do however think the naming will hurt the general adoption of the language, due to it sounding like any other esoteric language. Such as Brainfuck, Pikachu, Rockstar, LOLCODE, etc.

**Comment by bfiete** [comment] 2020-04-30 16:50
This issue will come up again and again, just leave this open. Lots of people hated the name Rust at first also, but now that's just the name.

**Comment by awulkan** [comment] 2020-04-30 17:27
I guess that true. I'd say that Rust is a bit more neutral for a name though. Anyway, if this issue is going to remain open I'll at least unsubscribe from it.

Good luck with the language (not being sarcastic, I'll check back on it every now and then).

**Comment by sukhchain99** [comment] 2020-04-30 18:18
![IMG_20200430_234030](https://user-images.githubusercontent.com/59991555/80744880-fa307600-8b3c-11ea-8097-51c7cf606253.jpg)

Pun intended!

**Comment by sukhchain99** [comment] 2020-04-30 19:42
![IMG_20200501_011051](https://user-images.githubusercontent.com/59991555/80752153-ab88d900-8b48-11ea-87e4-3b7c68031ad8.jpg)

Since BEEF is also a valid hexadecimal number. A small meme.

**Comment by targrub** [comment] 2020-05-01 01:12
How about COW?  Copy On Write is a thing, and the cow graphics for the installer are adorable.

**Comment by sukhchainn** [comment] 2020-05-01 06:48
![BF_Logo](https://user-images.githubusercontent.com/32098299/80787878-4e6f4080-8ba5-11ea-8705-dbbf129a7300.png)

Simple concept art as a prototype. I know it could be made better but I made it in Kolotpaint which is Linux equivalent to MS Paint so it doesn't look very nice but if we try this concept in a better tool then I'm sure it would come out better.

**Comment by sukhchain99** [comment] 2020-05-01 06:51
![IMG_20200501_091215](https://user-images.githubusercontent.com/59991555/80788255-42d04980-8ba6-11ea-8d93-2145558b086c.jpg)

Take this, hate us!

**Comment by sukhchainn** [comment] 2020-05-01 07:21
@bfiete as you already mentioned before, I am assuming that you are still looking for a Logo for BeefLang. If you could just tell me what kind of Logo you want, it would make it easier to design it.
Like what values should the Logo symbolize or if you prefer a certain theme over others?

**Comment by sacredbirdman** [comment] 2020-05-01 09:01
@sukhchain99 Yup, it'd be good to know a bit about the values and sentiments that a logo should try to convey :) That being said here's another (a bit punny) idea for the logo =)

It's Bee F

<img width="312" alt="Screenshot 2020-05-01 at 11 55 36" src="https://user-images.githubusercontent.com/43012733/80794751-647c0180-8ba3-11ea-860a-fbfaff35b220.png">

**Comment by HydrogenC** [comment] 2020-05-01 11:02
These logos look great, hope that one of them will be accepted.

**Comment by sukhchain99** [comment] 2020-05-02 09:16
Title: Got some sensibilities?

<img src="https://user-images.githubusercontent.com/59991555/80859974-4507d600-8c82-11ea-8719-aee44ad62ac3.jpg" alt="polterhousebeef" width="500"/>

Comment: This is pixel art and on some devices it may appear blurred.

**Comment by slier81** [comment] 2020-05-05 13:49
I agree with OP..Im sorry if others might find it funny, but the reason I dont use this language is because of its name. I mean Beef? Dont end up like `Go`, its hardly googleable.. Plus at the homepage of the language that is a picture of a piece of meat..

I mean, whose gonna take this language seriously with those kind of attribute..

Don't take it negatively, I do really like the language, but i do have serious gripe with the name and the logo of the language. I cant take this language seriously..

**Comment by Zen12** [comment] 2020-05-07 13:05
I think, it's a good idea to have a dumb name in language, it won't attract naive developers. That make decisions based on language name and not benchmark it.  At least in WIP stage... 

Personally, I don't want that Beef-community to transform in to something like Unity-community...

**Comment by nj39** [comment] 2020-05-07 13:50
> the language will not rebrand and rename for the sake of conforming to a serious and professional tone. This project will enforce it's artistic right to attempt to be a great tool without conforming to the expected dry tone of the field.

@bfiete I'm probably grasping at straws here looking for technicalities in your wording, but let me dream: Are there *other* reasons that the project might change it's name? Or was that comment saying that you're not open to changing the name for any reason? I completely agree that a project should have its own "spirit" and not be all dry and professional! I am 1000% behind that 👍

So the joviality of the name is great, I think. The problem with the name is that it mixes this joviality with a term that currently implies very *real* large-scale, unnecessary suffering. Those two don't mix very well, I think. I grew up on a (dairy) farm, and my dad currently farms Angus cattle, so I'm not going off some peta campaign here. It's really unpleasant when you see what these animals have to go through to get to our plate. If you watch [this video](https://youtu.be/VizpLk263iM?t=28) (it has no blood or gore at all) through to the 2 minute mark, you'll get a taste of what comes to mind for many people when they think about the word beef. [This documentary](https://www.reddit.com/r/videos/comments/f1la9r/joaquin_phoenix_just_used_his_best_actor_oscar/) does contain footage of violence, but is worth watching if you want to get a full sense of the suffering caused by the meat industry, and related industries. This is of course not to mention the [greenhouse gases, loss of biodiversity, ocean dead zones, and other problems](https://en.wikipedia.org/wiki/Environmental_impact_of_meat_production) caused by meat production. Altogether, it's not a pleasant thing to juxtapose with the cheery spirit of the project.

In any case, I really wish you well with this language whatever you choose! Maybe in the future "beef" will eventually come to refer primarily to the cell-culture version of the food, and then the current name would feel more comfortable :P

**Comment by Kolsky** [comment] 2020-05-11 16:45
Come on, are you serious? People are going too crazy with tolerance nowadays. It's the name of a programming language ftfs, it doesn't even change for the most of them, especially not for odd and weak reasons, and it can be almost anything (remember brainfuck).

**Comment by citrus3301** [comment] 2020-05-12 17:50
> Hi! Thank you for releasing this project. I'm often looking for a language that is powerful and fast to compile that helps with experimentation :)
> 
> This issue may sound like a joke but it's not. I find it uncomfortable to look at a logo representing a sliced dead animal. Growing large animals for human consumption is also a contributor to the climate problem. I guess so far I'm part of a small but growing minority, but I thought I should still raise awareness to this. I know changing a name is a hard issue to fix.
> 
> Maybe Beef could be an acronym of something less bloody and the logo match that acronym?
> 
> Or if the authors are strong believers in raising animals for human consumption an option would be to fork the project and replace every mention of Beef with another word to appeal to a wider audience? Leaf sounds similar and has the same number of characters, but leaf-lang exists already.
> 
> In any case thank you for considering this.

are you braindead

**Comment by revillo** [comment] 2020-05-15 15:53
I don't mind the name, but the raw steak logo is pretty jarring. My advice is to go with the living cow icon (that's already in the project) rather than the dead cow icon. I don't think anyone can be offended by a happy cow face and the matter could be put to rest for a while.

Language itself looks perfect though, so stoked for this :)

**Comment by CorneliusCornbread** [comment] 2020-05-23 02:08
> ![beef_logo](https://user-images.githubusercontent.com/43012733/79054812-be4a7500-7c50-11ea-9228-d0bff23b39f3.png)
> Here's a simple idea based on the current name.

I love this logo. Looks great, super clever, and clean design and is super easy to read. Looks much better and less tacky than the current logo. I honestly think the logo should be changed not because it's related to another game or because it's "sliced dead animal" but just because it looks super dated and tacky.

**Comment by sacredbirdman** [comment] 2020-05-23 14:42
![beef_logo2](https://user-images.githubusercontent.com/43012733/82733460-9bfe4980-9d1c-11ea-9282-9ed2e81dc334.png)
Thanks for the feedback. I gave this idea a new look with fresh eyes and came up with this design.

**Comment by EnokViking** [comment] 2020-05-28 01:00
> ![beef_logo2](https://user-images.githubusercontent.com/43012733/82733460-9bfe4980-9d1c-11ea-9282-9ed2e81dc334.png)
> Thanks for the feedback. I gave this idea a new look with fresh eyes and came up with this design.

It looks nice, >but< doesn't quite convey the message properly imo. It looks like FB or maybe even F3 which doesn't make much sense in this context and your previous one, which also looks nice, suffer from the same problem.

**Comment by dsoronda** [comment] 2020-06-11 07:43
How about name : Lion ? it's "king of animals", so this could be "king of programming languages" ?
Just my 2c.

**Comment by tjpalmer** [comment] 2020-07-11 02:21
Could keep the name Beef but have a beefy arm as the logo, a la Trogdor.

**Comment by sgf** [comment] 2020-11-05 08:43
![image](https://user-images.githubusercontent.com/2557696/98217540-9a9ca280-1f85-11eb-8457-64e037ca6006.png)

 fried beef

**Comment by fourst4r** [comment] 2020-12-03 20:14
> Dont end up like `Go`, its hardly googleable..

Used Go for 3 years and can say this is a non-issue, you simply type "golang" to your searches instead. "Beeflang" is perfectly fine and gives good search results.

As for changing the logo to a picture of a buff arm, well then you'll get a new issue about the toxic masculinity of it...

**Comment by Shadowblitz16** [comment] 2020-12-10 23:22
what about something like C4, BLang, Strut, Zest, Clutch, Rune

I would just look up a programming language generator and check if there is something googleable already.

**Comment by citrus3301** [comment] 2020-12-21 18:52
> As for changing the logo to a picture of a buff arm, well then you'll get a new issue about the toxic masculinity of it...

TRUE, lol

**Comment by timmyjose** [comment] 2021-12-21 07:42
> > Is there really a community of vegan programmers that get offended by the mention or sight of meat?
> 
> Is there really a community of vegan programmers that get offended by the sight of meat? I'm not sure. Is there a community of rampant elitists that go out of their way to shun replies with reactions to create the illusion of support behind an exclusive idea. Hacking has historically been an inclusive community to such an extent the only requirements were a shitty modem and a computer; the most divisive thing to exist was the GIMP abbreviation. Slapping a rendition of meat, a produce 8% of the worlds population has deemed immoral, is the last thing any sane project manager should consider. Why yes we should turn away 15%⋂8% of potential gamedevs, langdevs, and related (*15% hindu, 8% vegetarian, 1% vegans, some overlap worthy of note)

Oh, get over yourself.

**Comment by timmyjose** [comment] 2021-12-21 07:46
> > the language will not rebrand and rename for the sake of conforming to a serious and professional tone. This project will enforce it's artistic right to attempt to be a great tool without conforming to the expected dry tone of the field.
> 
> @bfiete I'm probably grasping at straws here looking for technicalities in your wording, but let me dream: Are there _other_ reasons that the project might change it's name? Or was that comment saying that you're not open to changing the name for any reason? I completely agree that a project should have its own "spirit" and not be all dry and professional! I am 1000% behind that 👍
> 
> So the joviality of the name is great, I think. The problem with the name is that it mixes this joviality with a term that currently implies very _real_ large-scale, unnecessary suffering. Those two don't mix very well, I think. I grew up on a (dairy) farm, and my dad currently farms Angus cattle, so I'm not going off some peta campaign here. It's really unpleasant when you see what these animals have to go through to get to our plate. If you watch [this video](https://youtu.be/VizpLk263iM?t=28) (it has no blood or gore at all) at least through to the 2 minute-ish mark, you'll get a taste of what comes to mind for many people when they think about the word beef. [This documentary](https://www.reddit.com/r/videos/comments/f1la9r/joaquin_phoenix_just_used_his_best_actor_oscar/) does contain footage of violence, but is worth watching if you want to get a full sense of the suffering caused by the meat industry, and related industries. This is of course not to mention the [greenhouse gases, loss of biodiversity, ocean dead zones, and other problems](https://en.wikipedia.org/wiki/Environmental_impact_of_meat_production) caused by meat production. Altogether, it's not a pleasant thing to juxtapose with the cheery spirit of the project.
> 
> In any case, I really wish you well with this language whatever you choose! Maybe in the future "beef" will eventually come to refer primarily to the cell-culture version of the food, and then the current name would feel more comfortable :P

With all due respect, kindly sod off. If you really wish to do something useful instead of simply flapping your gums, go join some activism group and help people/causes out in real life. Leave the man alone - it's his language, his choice. Deal with it, or get out.

**Comment by timmyjose** [comment] 2021-12-21 07:52
> Or if the authors are strong believers in raising animals for human consumption

This is where I stopped taking your seriously - silly strawmen arguments. Well, guess what, I love meat, and I don't care about animals being slaughtered for it. It's only Nature. You can choose not to like it - that's your prerogative, but you have absolutely no right to impose your worldview on others. That's disrespectful, rude, and more than a bit naive. If you wish to help improve the way animals are raised, do something about it in real life instead of mere virtue-signalling. Ridiculous.

**Comment by rinzwind5** [comment] 2021-12-22 06:36
It is a bad name, marketing wise. And obviously no one takes brainfuck serious as a language. Beef is a nice surprise, so I can ignore the bad and dumb naming. BC, BeeCee (Better C)? HappyCow (it has a website already ;)? 

"big muscles arm" as logo is an easy improvement. Thanks for reading.

**Comment by sgf** [comment] 2021-12-22 07:07
just do call **bf-lang**,less is more.
bf is keep the reading same as old (Beef).

**Comment by timmyjose** [comment] 2021-12-22 07:59
> just do call **bf-lang**,less is more. bf is keep the reading same as old (Beef).

That's already being used by Brainfuck though (specifically, the extension, `.bf`).

**Comment by ReeceSX** [comment] 2021-12-23 14:00
> Oh, get over yourself.

Says you responding to what feels like a 2 year old comment to seethe.  


> Come on, are you serious? People are going too crazy with tolerance nowadays. It's the name of a programming language ftfs, it doesn't even change for the most of them, especially not for odd and weak reasons, and it can be almost anything (remember brainfuck).
> With all due respect, kindly sod off. [...]  go join some activism group and help people/causes out in real life. Leave the man alone - it's his language, his choice. Deal with it, or get out

Yea, `(*15% hindu, 8% vegetarian, 1% vegans, some overlap worthy of note)` as I already pointed out will "sod off." That's exactly why me and my friends are hacking on V8 instead of taking shitlangs with memenames seriously - especially when their authors are hell bent on using controversial (idc what your opinion is, defer to the states) iconography. 

You're a moron if you think this is about tolerance and not the talent you're quite literally telling to sod off

**Comment by timmyjose** [comment] 2021-12-24 02:57
> > Oh, get over yourself.
> 
> Says you responding to what feels like a 2 year old comment to seethe.
> 
> > Come on, are you serious? People are going too crazy with tolerance nowadays. It's the name of a programming language ftfs, it doesn't even change for the most of them, especially not for odd and weak reasons, and it can be almost anything (remember brainfuck).
> > With all due respect, kindly sod off. [...]  go join some activism group and help people/causes out in real life. Leave the man alone - it's his language, his choice. Deal with it, or get out
> 
> Yea, `(*15% hindu, 8% vegetarian, 1% vegans, some overlap worthy of note)` as I already pointed out, I will "sod off." That's exactly why me and my friends are hacking on V8 instead of taking shitlangs with memenames seriously - especially when their authors are hell bent on using controversial (idc what your opinion is, defer to the stats) iconography. https://cyberia.tokyo/notice/ADBIdQWoMm3jLY1V9U; https://gitea.reece.sx/AuroraMiddleware/v8; https://gitea.reece.sx/AuroraSupport/AuroraV8PP; + other internal shit. Case in point, I know we wont ever contribute to this even though we could; and the fact that this is even being discussed proves the point.
> 
> You're a moron if you think this is about the meme of 'tolerance and inclusion' and not the talent you're quite literally telling to sod off

Quod erat demonstrandum. Calm down before you get an aneurysm. If you cannot take it, don't try and give out unsolicited advice, especially to the creator of a project. I'm sure the creator of Beef is not the least bothered without the inclusion of your "hacking" talents. If it were about the talent, you wouldn't have harped on the non-technical aspects of it. If you did, then you're being disingenuous. Again, get over your unseemly self, and piss off.

**Comment by ReeceSX** [comment] 2021-12-24 13:49
> I'm sure the creator of Beef is not the least bothered without the inclusion of your "hacking" talents. If it were about the talent, you wouldn't have harped on the non-technical aspects of it. I


https://www.youtube.com/channel/UCsL-E9RHk2HYurKM59_-jEQ/videos versus your sea of java trash. I haven't even mentioned "hacking," but the only thing you could've realistically found were my personal Java projects from my midteens. Keep larping.

**Comment by timmyjose** [comment] 2021-12-25 05:21
@ReeceSX 

Scratch an SJW, find a blathering idiot of a hypocrite.

>It's funny you put "hacking" in quotes. https://www.youtube.com/channel/UCsL-E9RHk2HYurKM59_-jEQ/videos versus your sea of java trash and notes citing intent to skid LLVM frontends. 

You do realise that I have an actual job that I do for a living, and what I put on my github is not only my own business, but for my own fun. Heh. Kindly direct your misplaced ad hominem elsewhere - it's very boring.

>My comment was clearly pointing out fact there are more worthy projects that people would choose over beef. 

Why are you here then? The creator is doing what he clearly likes doing, so I fail to see how that is any of your business especially with regards to the way the project is being run, and which direction it ought to go in.

> I don't see how maintaining a MSVC fork of V8 with strip downed dependencies and a more minimalistic build chain doesn't constitute as "hacking" worthy of note, at least in terms of contributing to an ecosystem of a language. Especially if i go through with my poc of linking JIT'd code as ELF and PE binaries. V8 has never had that functionality, JIT-less mode is too much of a performance hit for real time applications, and the only project that attempted it before is years old. 

I'm beginning to detect a deep sense of insecurity and false bravado in there. Are you sure you're all right (unironically). Maybe if you stopped trying so hard, people might actually listen to you in earnest, but the bigger problem is your abject lack of social and communication skills. Perhaps you should work on those first - that would help you much more than contributing to an Open Source projects.

> Except for high school level Java that doesn't even follow Oracles conventions, what do you offer and why should we care? If you believe I have no position to speak, you certainly don't. 

Yes, as I mentioned before, I actually do work for a living, you know. Moreover, you clearly have no idea what you're talking about. No offence, but I don't think you've ever worked in a real corporate company, have you? Of course not. No wonder your view of the world is not only so constrained, but also replete with oozing insecurity, as if you have to prove something not only to others, but also to yourself. That's not a healthy way of living, son.

>As someone who has hacked on languages before, as someone who is constantly looking for scripting engines, as someone who does care about the low level details as fucking reverse engineer who rewrote the entire asset pipeline for a AAA title speaking to someone who at best can point to a boring high level compiler and language notes as empty as tho, yea, this is up my ally.

Please take this to /r/IAmVerySmart, and stop boring me (and others I'm sure). Again, maybe stop trying to hard to say something (ironically, which is not even apropos to this whole thread). Ad Hominem, Strawman, Arguing from Consequence, Appeal to Authority, Appeal to Fear... you're  coming across as a walking bag of logical fallacies. My advice is to stop making an exhibition of yourself in public.

> Referring to my group of friends I can speak for, yes retard

Ouch. That definitely ages you right there (along with the whole bizarre comment), or at least your mental age.

My advice to you can be summed up thusly:

1. The project belongs to the creator, and he himself can decide what direction to take the project in. Stop embarrassing yourself by trying to hijack the project.

2.  Work on your self-esteem issues.

3.  Work on your communication skills ("soft skills"). That's the part that will help you most.

4. Stop taking yourself so seriously, and go back to step 2. 

I actually can't even get angry at your bizarre rant because I actually feel a smidgen of pity for you. Just a wee bit.

Cheers.

**Closed** 2022-03-31 14:51 UTC
