### ISSUE TITLE
[Bug] IDE cannot find MSVC tools folder 

### ISSUE THREAD

**Issue by Jonathan-Racaud** [beefytech/Beef#327] opened 2020-06-05 10:02 UTC
Hello,

After updating Visual Studio 2019 Community Edition and the build tools to the latest version (16.6.1) the Beef editor cannot find the tools because it remembers a previous version:

```Failed to execute "D:\Programs\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64/link.exe"```

The new path is for the folder with version ```14.26.28801```. However, when opening the Beef IDE settings (File->Preferences->Settings) and closing the Settings properties window (without modifying anything), it now finds the right folder and building succeed.

This behavior comes back after every launch of the Beef IDE.

Beef IDE version: 0.42.4
Windows: Windows 10 x64 1909

**Comment by bfiete** [comment] 2020-06-05 15:45
After it's set to the right value and you close the IDE, look at BeefSettings.toml in your install directory (ie: C:\Program Files\BeefLang\bin) - are the paths correct or do they show the old version still?

If they show the old version- what if you modify other settings, do those get saved on exit?

**Comment by Jonathan-Racaud** [comment] 2020-06-05 16:13
Indeed the IDE didn't write the new settings in the BeefSettings.toml. Actually the Save All action doesn't work when the IDE is not run as administrator. It cannot write to C:\Program Files. After running as administrator the settings are kept.

Here's how to reproduce the issue:
1. Install Beef 0.42.4 using BeefSetup_0.42.4.exe run as administrator
  a. Without administrator status the installer cannot install into C:\Program Files\BeefLang. The *Install for all* option fails and if we say no to the popup that follows, the rest of the installation fails
2. Start the IDE without the administrator status
3. Try the Save All action (ctrl+shift+s), the IDE will tell that it cannot write to the file BeefSettings.toml

Repeating steps 2 and 3 when running as administrator, there's no problem to write in the Program Files\BeefLang folder.

I also tried installing Beef without the *Install for all* option and the issue seems to not exist because all the files are in a location the Windows' user has the right to write.

I didn't try to keep all the options ticked and changing the installation folder to another location.

**Comment by bfiete** [comment] 2020-06-05 17:02
Do you have higher-than-default UAC control settings?

**Comment by bfiete** [comment] 2020-06-05 17:09
I'm a little confused- it seems like there are other users having this installation issue and I don't understand it.

In step 1 you say "Install Beef 0.42.4 using BeefSetup_0.42.4.exe run as administrator". You say you run it as admin but you STILL get an elevation popup? And... then you say NO to that? I don't understand.

I would love to reproduce this issue where the file are installed to Program Files but are not writable, but I can't figure out how to.

**Comment by bfiete** [comment] 2020-06-05 17:14
Oh, wait, I do see an issue but it's like this:
1) Run the setup as admin. Install with default options, there will be NO elevation popups.
2) Start IDE without admin. Save All fails.

But that doesn't sound like what you described in step 1. Also- why did you explicitly select to run the installer as admin?

**Comment by Jonathan-Racaud** [comment] 2020-06-05 17:39
Sorry my explanations were not clear. I hope the one below are better.

I see two different behaviors:

## A. Installing as normal user
1. Run the installer normally, do not explicitly run as administrator
2. Keep all options ticked
3. Select Yes on the UAC Popup
4. The elevation fails
![Installation_Step_03](https://user-images.githubusercontent.com/4101737/83905713-6ddc2900-a762-11ea-891d-daa2cf641c0a.png)
5. Select no
6. Try install again
7. Fails and sometimes crash
![Installation_Step_04](https://user-images.githubusercontent.com/4101737/83905999-feb30480-a762-11ea-94ca-7b70c43441fe.png)
[Crash Dump file](https://we.tl/t-n20JRLBt7R)

## B. Installing as administrator
1. Right click installer -> Run as administrator
2. Select Yes on the UAC Popup
3. Installs in default folder with success
4. Close the IDE
5. Launch the IDE as normal user
6. Save All fails
![Fails_to_write_file](https://user-images.githubusercontent.com/4101737/83906454-e42d5b00-a763-11ea-8e24-e433a553c8ae.png)

So the reason I initially ran the installer as administrator was to have the installation located in C:\Program Files\BeefLang which I couldn't do without running as admin. In my case, the install for all user option is kind of unnecessary as I am the only user on my laptop.

### My UAC Settings
![UAC_Settings](https://user-images.githubusercontent.com/4101737/83906642-438b6b00-a764-11ea-9286-43d6e8d8aab1.png)

**Comment by bfiete** [comment] 2020-06-05 18:05
Thanks- that's helpful. One more thing- if you manually delete the BeefLang directory and run the installer as normal (not as admin), does saying Yes to the elevation work? I can't figure out why this elevation seems to fail for some people...

**Comment by bfiete** [comment] 2020-06-05 21:25
Alright- this was very useful. It turns out the root issue was a localization issue, which I should have figured. When you install to Program Files, the installer grants "Users" permission to the BeefLang directory so your non-elevated user can write to that directory still. The name "Users" was English-specific, so that ACL change failed. When you run as an admin the installer didn't even attempt to modify the ACL since it detected it already had privileges to write to Program Files... but then the IDE would fail to write later on when it was not elevated.

Both issues are fixed now -- we look up the Users user by its well-known SID number, and we properly perform the ACL modification when running the installer as admin. The change will be in tonight's nightly build...

**Closed by bfiete** 2020-06-05 21:25 UTC
Labels: bug
