### ISSUE TITLE
[Enhancement] Road to linq

### ISSUE THREAD

**Issue by xposure** [beefytech/Beef#808] opened 2021-01-13 02:01 UTC
- [x] Commit 33b9b87 crashes the IDE with Reverse, I imagine some of the issues here are related to each other.
 
 - [x] Comment 5f9d6b9 hangs the IDE (related to DefaultIfEmpty)

- [x] Commit 999fca4 in xposure/Beef.Linq has an issue with selecting the right ToDictionary
 

 - [x] This code does not work, for some reason iterator1 is unknown and just reports 'var'
EDIT: If you delete `			where TRight : concrete, IEnumerable<TSource>` it will crash the IDE
EDIT2: There are other versions of this that causes a crash too, the result of it all seems to be `Iterator.Wrap` if I change the code to the code below, all the bugs/crashes go away. 
```
			using(let iterator0 = Iterator<decltype(default(TLeft).GetEnumerator()), TSource>(right.GetEnumerator()))
			using(let iterator1 = Iterator<decltype(default(TRight).GetEnumerator()), TSource>(right.GetEnumerator()))
```

```
		struct Iterator
		{
			public static Iterator<decltype(default(TCollection).GetEnumerator()), TSource> Wrap<TCollection, TSource>(TCollection items)
				where TCollection : concrete, IEnumerable<TSource>
			{
				return .(items.GetEnumerator());
			}
		}

		struct Iterator<TEnum, TSource> : IDisposable
			where TEnum : concrete, IEnumerator<TSource>
		{
			internal TEnum mEnum;

			public this(TEnum items)
			{
				mEnum = items;
			}

			[SkipCall]
			public void Dispose() { }

		}

		extension Iterator<TEnum, TElem> : IDisposable where TEnum : IDisposable
		{
			public void Dispose() mut => mEnum.Dispose();
		}

		public static bool SequenceEquals<TLeft, TRight, TSource>(this TLeft left, TRight right)
			where TLeft : concrete, IEnumerable<TSource>
			where TRight : concrete, IEnumerable<TSource>
			where bool : operator TSource == TSource
		{
			using (let iterator0 = Iterator.Wrap<TLeft, TSource>(left))
			{
				var e0 = iterator0.mEnum;
				using (let iterator1 = Iterator.Wrap<TRight, TSource>(right)) //compiler is confused about the type
				{
					var e1 = iterator1.mEnum;
					while (true)
					{
						switch (e0.GetNext()) {
						case .Ok(let i0):
							{
								switch (e1.GetNext()) {
								case .Ok(let i1):
									{
										if (i0 != i1)
											return false;
									}
								case .Err:
									{
										switch (e1.GetNext()) {
										case .Ok:
											return false;
										case .Err:
											return true;
										}
									}
								}
							}
						case .Err:
							{
								switch (e1.GetNext()) {
								case .Ok:
									return false;
								case .Err:
									return true;
								}
							}
						}
					}
				}
			}
		}
```
 - [x] This code locks up the compiling process
```
		public static bool Contains<TCollection, TSource>(this TCollection items, TSource source)
			where TCollection : concrete, IEnumerable<TSource>
			where bool: operator TSource == TSource
		{
			var enumerator = items.GetEnumerator();
			while (enumerator.GetNext() case .Ok(let val))
				if(val == source)
					return true;

			return false;
		}

		[Test]
		public static void Contains()
		{
			let data = scope List<int>();

			var actual = data.Contains(2);
			Test.Assert(!actual);

			data.Add(2);

			actual = data.Contains(2);
			Test.Assert(actual);
		}
```

 - [x] If you check out xposure/Beef.Linq and open test project and try to format the one file in it, it corrupts the code. 

```
		[Test]
		public static void Take()
		{
			var data = scope List<int>();
			for(var i < 20)
				data.Add(i);

			var linq = data
						.Take(10);

			var count = 0;
			for(var it in linq)
				count++;

			Test.Assert(count == 10);
			Test.Assert(data.SequenceEquals(scope int[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9})  == true);
		}

		public static bool SequenceEquals<TLeft, TRight, TElem>(this TLeft left, TRight right)
			where TLeft : concrete, IEnumerable<TElem>
			where TRight : concrete, IEnumerable<TElem>
			where bool: operator TElem == TElem
		{
			var e0 = left.GetEnumerator();
			var e1 = right.GetEnumerator();
			while (true)
			{
				switch (e0.GetNext()) {
				case .Ok(let i0):
					{
						switch (e1.GetNext()) {
						case .Ok(let i1):
							if(i0 != i1)
								return false;
						case .Err:
							return false;
						}
					}
				case .Err:
					{
						switch (e1.GetNext()) {
						case .Ok(let i1):
						case .Err:
							return true;
						}
					}
				}
			}
		}
```

 - [x] Since .NET is using interfaces throughout, its allowed to do this optimization below. Since the types are concrete and Beef knows what they are, the following code won't work since it can verify that these casts will fail. The only solution I could think of is overloads which could be teadious, but doable. 

```

		public static int Count<T, TElem>(this T items)
			where T : concrete, IEnumerable<TElem>
		{
			//fast
			/*if (let list = items as List<TElem>)
				return list.Count;
			else if (let array = items as TElem[])
				return array.Count;*/

			//slow, .net has a stored `fastOnly` flag in places that will return -1 if it would execute the enumerator
			var count = 0;
			for (var it in items)
				count++;
			return count;
		}

```

- [x] We need `.` to be able to infer this scenario
```
		public static void Bar()
		{
			var data = scope List<(int x, int y, float z, float w)>();
			data.Add((1, 2, 3, 4));
			data.Add((4, 3, 2, 1));

			data.Foo(scope (it) => (x: it.x, y: it.y), scope .()); //doesn't work
			data.Foo(scope (it) => (x: it.x, y: it.y), scope List<(int x, int y)>());
		}

		public static void Foo<T, TElem, TSelector, TResult>(this T items, TSelector selector,  List<TResult> output)
			where T: concrete, IEnumerable<TElem>
			where TSelector: delegate TResult(TElem)
		{
			for(var it in items)
				output.Add(selector(it));
		}
```

 - [x] .net allows both a property Count and a extension function Count() to exist, determine if this is possible or if we need to rename the linq Count()
 
This method below can't be called when T is a List<TElem>
```
		public static int Count<T, TElem>(this T items)
			where T : concrete, IEnumerable<TElem>
		{
			//fast
			if (let list = items as List<TElem>)
				return list.Count;
			else if (let array = items as TElem[])
				return array.Count;

			//slow, .net has a stored `fastOnly` flag in places that will return -1 if it would execute the enumerator
			var count = 0;
			for (var it in items)
				count++;
			return count;
		}

```

Error is "can't perform invocation on int"
![image](https://user-images.githubusercontent.com/6292318/104793850-272bc400-5772-11eb-8d3b-d1ee90e8725d.png)

 - [x]  Supporting delegate return inference 

```
        public struct XYZ
        {
            public float t;
        }
            var items = new List<XYZ>();
            var r = items.Sum(x => x.t);
```

- [x] generic parameterization on the concrete return type of T.GetEnumerator() 

- [x] Type inference of TElem

```
static TElem Sum<T, TElem>(T t) where T: IEnumerable<TElem>, TElem : operator TElem + TElem
```

Implementation scenarios
Sum takes in a concrete IEnumerable<T> as well as a delegate of TResult(TElem) ... first scenario above
```
    public static
    {
        public static TResult Sum<T, TElem, TDlg, TResult>(this T it, TDlg dlg)
            where T: IEnumerable<TElem>
            where TDlg: delegate TResult(TElem)
            where TResult: operator TResult + TResult
        {
            var result = default(TResult);
            for(var elem in it)
                result += TDlg(elem);
            return result;
        }
    }
```

**Comment by bfiete** [comment] 2021-01-13 17:31
Type inference to TElem implemented at https://github.com/beefytech/Beef/commit/9510faafca9f6d5119eb104f79d1c964b356a8e6

With the anonymous types item- I'm still not seeing what feature anonymous types are supposed to implement that's not supported by tuples. It seems you want this:
```C#
          public struct xyz : this(float2 position, float rotation, int x, int y, int z){}
          List<xyz> items = scope .();
          let e = items.Select( it => (p: it.position, r: it.rotation) );
          //e would need to be a concrete IEnumerable<result>
```
And of course delegate return inference needs to work too.

**Comment by bfiete** [comment] 2021-01-13 18:19
Also you're missing this piece:
`static WhereEnum<TEnum> Where<T, TElem, TEnum>(this T val, bool (TElem) pred) where T : IEnumerable<TElem> where TEnum : decltype(T.GetEnumerator())`

You need a "WhereEnum" that wraps (stores) the concrete enumerator that will be returned from `IEnumerable<TElem>`.
That's not the actual syntax I'm proposing, just a description of the functionality needed.

**Comment by bfiete** [comment] 2021-01-14 14:30
Lambda return inference at https://github.com/beefytech/Beef/commit/bb12a4ec20cf1d4da59c8021a4ff4bd9e2a0cea7

Check out https://github.com/beefytech/Beef/blob/master/IDEHelper/Tests/src/Generics.bf#L244 /
https://github.com/beefytech/Beef/blob/master/IDEHelper/Tests/src/Generics.bf#L308

**Comment by bfiete** [comment] 2021-01-14 14:32
One last piece, still - generic parameterization on the concrete return type of `T.GetEnumerator()`. The feature to implement this will open a whole new class of metaprogramming in BeefLang (you'll see)...

**Comment by xposure** [comment] 2021-01-14 22:39
Yea, was a misunderstanding from me, I though you said you needed to do (p: xyz) rather you said it was already there.
I swapped it out for GetEnumerator

**Comment by xposure** [comment] 2021-01-16 00:37
I added another piece to the top that would be useful to have. Here it says invalid use of type, this isn't the actual intended usage with Lists as i said in chat, just demostrating the problem.

**Comment by bfiete** [comment] 2021-01-16 14:31
Concrete return inference should work now, see:
https://github.com/beefytech/Beef/blob/master/IDEHelper/Tests/src/Generics.bf#L276

Turns out it didn't actually need the new `comptype` feature.

**Comment by bfiete** [comment] 2021-01-16 14:43
',' inference issue fixed at https://github.com/beefytech/Beef/commit/df2c110de2931efa7637b36dd04234e2f71c671b

**Comment by bfiete** [comment] 2021-01-16 16:32
Fixed `Count` extension method issue at https://github.com/beefytech/Beef/commit/10d4047d0162a7c86a48bbc49a8ab1eb2aac55a8

The rules are a bit weird here - if the referenced member evaluates to a delegate/function then that is invoked, otherwise we check extension methods and then if we don't find one then we give an 'unable to invoke field' error from the previously-found field/prop.

**Comment by xposure** [comment] 2021-01-17 02:52
This code crashes the IDE (notice the typo on `TEnum`

```
		struct SelectEnumerator<TElem, TEnumm,  TDlg, TResult> : IEnumerator<TResult>
			where TDlg : delegate TResult(TElem)
			where TEnum : concrete, IEnumerator<TElem>
		{
			TDlg mDlg;
			TEnum mEnum;

			public this(TEnum e)
			{
				mEnum = e;
			}

			public Result<TResult> GetNext() mut
			{
				if(mEnum.GetNext() case .Ok(let val))
					return mDlg(val);

				return .Err;
			}
		}

```

**Comment by xposure** [comment] 2021-01-17 03:52
Also wondering if this puts us on the same page or if you have any other ideas/advice.

https://gist.github.com/xposure/2b091a32417fe2b2e36aedd0210afd7a

**Comment by bfiete** [comment] 2021-01-19 19:51
Boy, this multi-item is starting to feel a little unwieldy here.

**Comment by bfiete** [comment] 2021-01-19 20:06
'This code locks up the compiling process' fixed at https://github.com/beefytech/Beef/commit/20d8ae279c543639b974f6fd792c0333735a1bb2

**Comment by bfiete** [comment] 2021-01-19 21:12
`The following code can't determine TElem when these methods are used inside.` fixed at https://github.com/beefytech/Beef/commit/8f5f06bdb10584e11b5496cbf3bd5566bddc0a33

**Comment by bfiete** [comment] 2021-01-19 21:21
`Commit 33b9b87 crashes the IDE` doesn't reproduce for me - fixed?

**Comment by bfiete** [comment] 2021-01-19 21:23
`Comment 5f9d6b9 hangs the IDE` doesn't reproduce for me - related to other freeze issue and fixed now, too?

**Comment by bfiete** [comment] 2021-01-19 21:52
`Commit 999fca4 in xposure/Beef.Linq has an issue with selecting the right ToDictionary` fixed at https://github.com/beefytech/Beef/commit/d5203f44dbd749a54228307b5d04a443f1a9d06b

**Comment by bfiete** [comment] 2021-01-20 14:31
I'm going to definitely add this library to the standard CI tests...

**Comment by bfiete** [comment] 2021-01-20 14:44
`This code does not work, for some reason iterator1 is unknown and just reports 'var'` fixed at https://github.com/beefytech/Beef/commit/e35318c6880cfd0f002b14d0a9a18f45645ef851
Also there was a small bug in your SequenceEquals. It's in the test suite now at:
https://github.com/beefytech/Beef/blob/master/IDEHelper/Tests/src/Generics2.bf#L66

**Comment by xposure** [comment] 2021-01-20 14:45
Awesome, would you rather one master issue with issues linking back to it instead of just a big mega issue?

**Comment by bfiete** [comment] 2021-01-20 14:47
Let's just make separate issues from now on.

**Comment by bfiete** [comment] 2021-01-20 14:49
On the Sum with nullables:
This is documented here https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum?view=net-5.0
It appears these _are_ for summing up `IEnumerable<T?>`s.
The logic is that is the list is empty or _any_ element is nullable then null is returned. The good news is that this should _already work_ with no additional work, since the nullable + operator already has that null-propagating behavior, and `default(T?)` does produce null.

**Comment by bfiete** [comment] 2021-01-20 15:02
`Since .NET is using interfaces throughout, its allowed to do this optimization below.`
1) You can either do overloads, as you mentioned
2) You can just do what they did. This optimizes "pretty well" - the type check will be statically determined since the casts can all be statically proven or disproven at monomorphization-time. It still needs to handle the "null" case which will drop down into the slow path still, though.
3) The following SHOULD be the ideal way, but typeof comparisons don't appear to be properly const-evaluable. Fixing that now...
```C#
public static int Count<T, TElem>(this T items)
	where T : concrete, IEnumerable<TElem>
{
	if (typeof(T) == typeof(List<TElem>))
		return (items as List<TElem>).Count;
	if (typeof(T) == typeof(TElem[]))
		return (items as TElem[]).Count;
	
	//slow, .net has a stored `fastOnly` flag in places that will return -1 if it would execute the enumerator
	var count = 0;
	for (var it in items)
		count++;
	return count;
}
```

**Comment by bfiete** [comment] 2021-01-20 15:26
Ok, now the typeof comparisons properly const-eval
https://github.com/beefytech/Beef/commit/7e307b2f0d01a24dd57f5e6945f043486067f768

The code in option 3 will be just as fast as option 1 now.

**Comment by xposure** [comment] 2021-01-20 17:39
> On the Sum with nullables:
> This is documented here https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.sum?view=net-5.0
> It appears these _are_ for summing up `IEnumerable<T?>`s.
> The logic is that is the list is empty or _any_ element is nullable then null is returned. The good news is that this should _already work_ with no additional work, since the nullable + operator already has that null-propagating behavior, and `default(T?)` does produce null.

```
Binary operation for 'System.Linq.Sum<System.Collections.List<int?>, int?>(System.Collections.List<int?> items)' must result in 'int?' from binary operation 'int? + int?' at line 146:23 in c:\Users\cphillipd83\Documents\Git\Beef.Linq\src\test\src\EnumerableTests.bf
    let actual = data.Sum();
```

**Comment by bfiete** [comment] 2021-01-20 17:43
`If you check out xposure/Beef.Linq and open test project and try to format the one file in it, it corrupts the code.` fixed at https://github.com/beefytech/Beef/commit/48f2ec42f58bbdcf0cd734ea7c207eb4c2705438

**Closed** 2021-01-20 18:09 UTC
