### ISSUE TITLE
[BUG] compile error on Release mode

### ISSUE THREAD

**Issue by kochol** [beefytech/Beef#812] opened 2021-01-16 12:51 UTC
I get a compile error only when compiling in Release mode and in debug everything works fine.
```
ERROR: The type 'T' must be a value type in order to use it as parameter 'T' for 'T?' at line 124:14 in Atma.Json\src\Atma.Json\src\JsonConverterStructs.bf
    let n = (Nullable<T>*)target;
```
First the error is not clear at least I want to see what was the T when I got this error?
Is it a compile bug? Because it only happens in release mode

here is my repo
https://github.com/kochol/blockheroes

the error is here
https://github.com/kochol/Atma.Json/blob/3d6a6506f5fd08bef6ca2250a48dc9d9afdb3d0d/src/Atma.Json/src/JsonConverterStructs.bf#L124

**NOTE: ** The code is in atmajson branch for blockheroes and Ariyana repos

**Comment by bfiete** [comment] 2021-01-16 15:14
What version are you using? Does this reproduce for you on the latest nightly build?

**Comment by kochol** [comment] 2021-01-16 16:03
I use the latest nightly build

**Comment by bfiete** [comment] 2021-01-16 16:34
I'm not able to reproduce this on the latest nightly....

So if you just start up the latest IDE from scratch, select Release and compile, you will immediately get that error? Or are there some other steps I need to take?

**Comment by bfiete** [comment] 2021-01-16 16:35
I just get the 3 warnings from ImGui and that's it.

**Comment by kochol** [comment] 2021-01-17 04:18
> I'm not able to reproduce this on the latest nightly....
> 
> So if you just start up the latest IDE from scratch, select Release and compile, you will immediately get that error? Or are there some other steps I need to take?

Did you switch to atmajson branch on Ariyana and Block heroes repos?

Yes I get error after hit F7 in Release mode.

**Comment by kochol** [comment] 2021-01-17 11:00
[blockheroes.zip](https://github.com/beefytech/Beef/files/5825905/blockheroes.zip)

I uploaded the codes for you
I deleted the .lib files to reduce the size

**Comment by kochol** [comment] 2021-01-17 14:02
I also find out when I compile in Debug for the first time I get this error but when I compile again. The error will gone.

**Comment by bfiete** [comment] 2021-01-19 00:07
The error given was correct, but it should have been occurred on every compilation. A fix for that missing error is incoming.

The problem is that `Nullable<T>` can only be used on value types which you would normally constrain with `where T : struct`. Or you can just have a `where T : var` constraint.

**Comment by bfiete** [comment] 2021-01-19 00:12
@xposure

**Comment by bfiete** [comment] 2021-01-19 00:12
Can be fixed with a `where T : var` here https://github.com/xposure/Atma.Json/blob/master/src/Atma.Json/src/JsonConverterStructs.bf#L62

**Closed** 2021-01-19 13:52 UTC
